### ISSUE TITLE
Windows: WARN:smartdns::server::udp:36: error receiving message on udp_socket (and fix)

### ISSUE THREAD

**Issue by chmichael** [mokeyish/smartdns-rs#391]
Only in windows it throws and UDP warning:
WARN:smartdns::server::udp:36: error receiving message on udp_socket: An existing connection was forcibly closed by the remote host. (os error 10054)

Here's the solution for windows only in rust:
https://github.com/shadowsocks/shadowsocks-rust/issues/262#issuecomment-633112782
You'll need to import the winapi package too: https://crates.io/crates/winapi

from notes:
Ignoring UdpSocket's WSAECONNRESET error
This is because UdpSocket::recv_from may return WSAECONNRESET
if you called UdpSocket::send_to a destination that is not existed (may be closed).
It is not an error. Could be ignored completely.
We have to ignore it here because it will crash the server.

I hope you add it soon
discussion: https://github.com/mokeyish/smartdns-rs/discussions/368

**Comment by mokeyish** [comment]
Thanks, Looks good, I'll check it out this weekend.

There is already a ready-made code, you can just adjust it and give it a try.


The corresponding code is here:

https://github.com/mokeyish/smartdns-rs/blob/669e379d0edbca4439f7a2a74feccdc8f2a80736/src/server/mod.rs#L330-L350

**Comment by mokeyish** [comment]
I solved this problem a long time ago. At that time, the program crashed. I just changed the error to a warning so that it would not affect the use.


https://github.com/hickory-dns/hickory-dns/issues/1913#issue-1641969705

**Comment by chmichael** [comment]
Done and compiled! No more UDP errors in Windows! 

btw it needs the "unsafe declaration" cause of "WSAIoctl". 
Maybe you can find somewhere else safe ?

CARGO.TOML add: 
[target.'cfg(windows)'.dependencies]
...
// add code below
winapi = { version = "0.3.9", features = ["mswsock", "winsock2"] }
...


MOD.RS:
```
    pub fn udp(
        sock_addr: SocketAddr,
        bind_device: Option<&str>,
        bind_type: &str,
    ) -> io::Result<UdpSocket> {

        // add code below
        use std::{mem, os::windows::io::AsRawSocket, ptr};
        use winapi::{
            shared::minwindef::{BOOL, DWORD, FALSE, LPDWORD, LPVOID},
            um::{
                mswsock::SIO_UDP_CONNRESET,
                winsock2::{WSAGetLastError, WSAIoctl, SOCKET, SOCKET_ERROR},
                },
        };
       
        ...        
        let udp_socket = std::net::UdpSocket::bind(sock_addr)?;`

        // add code below
        let handle = udp_socket.as_raw_socket() as SOCKET;
        let mut bytes_returned: DWORD = 0;
        let mut enable: BOOL = FALSE;
	    unsafe { 
		    let ret = WSAIoctl(
              handle,
              SIO_UDP_CONNRESET,
              &mut enable as *mut _ as LPVOID,
              mem::size_of_val(&enable) as DWORD,
              ptr::null_mut(),
              0,
              &mut bytes_returned as *mut _ as LPDWORD,
              ptr::null_mut(),
              None,
            );

  	        if ret == SOCKET_ERROR {
               use std::io::Error;

              // Error occurs
              let err_code = WSAGetLastError();
              return Err(Error::from_raw_os_error(err_code));
            }
		};
```

ps: i did update all the cargo packages to the latest versions and only rustls has a breaking change in windows.

**Comment by mokeyish** [comment]
Calling Windows API, unsafe seems to be inevitable. 

But I prefer to use 
https://crates.io/crates/windows
instead of winapi, which has not been updated for a long time.

**Comment by chmichael** [comment]
Windows GNU build produces UDP 38 error

**Comment by mokeyish** [comment]
Indeed, GNU has not solved this problem. I don't have time to find a solution, and if it is solved, it will only reduce the log warning, which does not affect the use.
